# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'your-container-image-name:$(build.buildId)'

steps:
- displayName: 'Tomcat docker build'
  script: |
    docker build -f Dockerfile -t $(imageName) .
    docker login -u mpradha1 -p Ganesh14 docker.io
    docker push docker.io/pradhanm/tomcat-test
  
